
build:

  image: ubuntu:devel
  stage: build

  script:  
    - apt update
    - apt full-upgrade --yes
    - apt install --yes make cmake clang19

    - make --version
    - cmake --version
    - clang --version
