pages:

  image: deanturpin/gcc
  stage: build
  artifacts:
    paths:
      - public

  script:
    # Update
    - apt update
    - apt full-upgrade --yes

    # Version check
    - echo '```' >> index.md
    - neofetch  >> index.md
    - make --version >> index.md
    - cmake --version >> index.md
    - ninja --version >> index.md

    # Build and run
    - make >> index.md

    # Tidy up
    - echo '```' >> index.md
    - date >> index.md

    # Publish
    - apt install --yes pandoc
    - mkdir public/
    - pandoc --standalone --to html5 --output public/index.html index.md
