pages:

  image: deanturpin/gcc
  stage: deploy
  artifacts: {paths: [public]}
  script:

    - apt update
    - apt install --yes libpcap-dev iputils-ping

    # Start code section
    - date | tee --append index.md
    - echo '```' | tee --append index.md

    # Create some traffic in the background
    - ping -c 200 turpin.dev&

    # Build and run
    - make | tee --append index.md

    # End code section
    - echo '```' | tee --append index.md

    # Publish
    - mkdir public/
    - pandoc index.md --standalone -f gfm -t html5 --output public/index.html
