pages:

  image: deanturpin/gcc
  stage: build
  artifacts:
    paths:
      - public

  script:
    # Update
    - apt update
    - apt full-upgrade --yes

    # Version check
    - echo '```' | tee --append index.md
    - neofetch | tee --append index.md
    - make --version | tee --append index.md
    - cmake --version | tee --append index.md
    - ninja --version | tee --append index.md

    # Build and run
    - make | tee --append index.md

    # Tidy up
    - echo '```' | tee --append index.md
    - date | tee --append index.md

    # Publish
    - apt install --yes pandoc
    - mkdir public/
    - pandoc --standalone --to html5 --output public/index.html index.md
