# Build the image and push to Docker registry
build:

  image: docker
  stage: build
  services: [docker]
  script:

    # Docker likes to have git
    - apk add git

    # Build the image for different hardware
    - docker buildx build -t deanturpin/wispa .
    - docker buildx build --platform linux/arm64/v8 -t deanturpin/gcc-arm64 

    # Push images to Docker registry
    - docker login -u deanturpin -p $DOCKER_ACCESS_TOKEN
    - docker push deanturpin/wispa
    - docker push deanturpin/wispa-arm64

pages:
  
  image: ubuntu:devel
  stage: deploy
  artifacts: {paths: [public]}
  script:
    
  - apt update
  - apt install --yes pandoc sloccount make
  
  # Start code section
  - date | tee --append index.md
  - echo '```' | tee --append index.md
  
  # Store last git commit message
  - echo "Last commit message '$(git log -1 --oneline)'" | tee --append index.md
  - echo | tee --append index.md
    
  # End code section
  - echo '```' | tee --append index.md
  
  # Report some dev stats
  - echo '## sloccount' | tee --append index.md
  - echo '```' | tee --append index.md
  - make stats | tee --append index.md
  - echo '```' | tee --append index.md
  
  # Publish
  - make publish
