
build:

  image: ubuntu:devel
  stage: build

  script:  

    # Update and install
    - apt update
    - apt full-upgrade --yes
    - apt install --yes make cmake clang

    # Version check
    - make --version
    - cmake --version
    - clang --version

    # Build
    - make
