
build:

  image: ubuntu:devel
  stage: build

  script:  

    # Update and install
    - apt update
    - apt full-upgrade --yes
    - apt install --yes neofetch make cmake ninja-build clang build-essential

    # Version check
    - neofetch
    - make --version
    - cmake --version
    - ninja --version
    - clang --version

    # Build and run
    - make
