pages:

  image: deanturpin/gcc
  stage: deploy
  artifacts: {paths: [public]}
  script:

    - apt update
    - apt install --yes libpcap-dev iputils-ping

    # Start code section
    - echo '```' | tee --append index.md

    # Create some traffic
    - ping -c 200 turpin.dev >& /dev/null &

    # Build and run
    - make | tee --append index.md

    # End code section and timestamp
    - echo '```' | tee --append index.md
    - date | tee --append index.md

    # Publish
    - cat index.md
    - mkdir public/
    - pandoc index.md --standalone -f gfm -t html5 --output public/index.html
