# Build the image and push to Docker registry
build:

  image: docker
  stage: build
  services: [docker]
  script:

    # Docker likes to have git
    - apk add git nmap

    # Build the image
    - docker buildx build -t deanturpin/wispa .

    # Create some network traffic in the background
    - nmap -A turpin.dev &
    
    # Run the image
    - docker run deanturpin/wispa

    # Push images to Docker registry
    - docker login -u deanturpin -p $DOCKER_ACCESS_TOKEN
    - docker push deanturpin/wispa
