build:

  image: deanturpin/gcc
  stage: deploy
  artifacts: {paths: [public]}
  script:

    # Start code section
    - echo '```' | tee --append index.md

    # Report versions
    # - neofetch | tee --append index.md
    # - make --version | tee --append index.md
    # - cmake --version | tee --append index.md
    # - ninja --version | tee --append index.md

    # Build and run
    - make | tee --append index.md

    # End code section and timestamp
    - echo '```' | tee --append index.md
    - date | tee --append index.md

    # Publish
    - cat index.md
    - mkdir public/
    - pandoc index.md --standalone -f gfm -t html5 --output public/index.html

