build:

  image: docker
  stage: build
  only: [main]
  services: [docker]
  script:

    # Build the image
    - apk add git
    - docker buildx build --no-cache  -t deanturpin/wispa .

    # Push images to Docker registry
    - docker login -u deanturpin -p $DOCKER_ACCESS_TOKEN
    - docker push deanturpin/wispa
